import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-white w-[100dvw] relative h-[100dvh]">
        <div className="w-full relative max-w-[400px] bg-[#00B1FF] h-full text-white flex flex-col overflow-hidden">
          <div className="flex-1 overflow-y-auto">{children}</div>
          <Navbar />
        </div>
      </body>
    </html>
  );
}
