import type { Metadata } from "next";
import "./globals.css";
import Navigation from "./components/navigation";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className="bg-gradient-svg w-[100dvw] relative h-[100dvh]">
                {/* Main container for the app content */}
                <div className="w-full main-application relative max-w-[400px] bg-[#00B1FF] h-full text-white flex flex-col overflow-hidden">
                    {/* Scrollable content */}
                    <div className="flex-1 overflow-y-auto">{children}</div>
                    {/* Fixed navigation at the bottom */}
                    <Navigation />
                </div>
            </body>
        </html>
    );
}
